name: 🔥 Bug Report
description: Create a bug report
labels: [ "bug" ]
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Tell us about the steps to reproduce the bug.
      value: |
        1.
        2.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected result, actual Result and additional information
      description: A clear and concise description of what you expected to happen and what happens instead
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots and Videos
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: input
    attributes:
      label: Crash Report or Log
      description: If applicable, please add a **link** to the crash report or log that was created when this issue occurred. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue.
    validations:
      required: false
  - type: input
    attributes:
      label: Mod Version
      description: The version of the mod you were using when the bug occurred
      placeholder: Tips-Forge-1.19.2-8.0.21.jar
    validations:
      required: true
  - type: input
    attributes:
      label: Mod loader and version
      placeholder: Forge 40.1.84 / Fabric x.x.x / Quilt x.x.x
    validations:
      required: true
  - type: input
    attributes:
      label: Minecraft Version
      description: The version of Minecraft you were using when the bug occurred
      placeholder: 1.19.2
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other Mods
      description: Please list any other mods that were running when the crash happened.
    validations:
      required: false
      placeholder: |
        architectury-4.9.84-forge
        RoughlyEnoughItems-8.3.549
  - type: markdown
    attributes:
      value: "Thank you for reporting!"