name: ✨ Mod Suggestion
description: Suggest changes to the mod
labels: [ "enhancement" ]
body:
  - type: textarea
    attributes:
      label: Describe the Suggestion
      description: What would you like to have changed?
    validations:
      required: true
      placeholder: Make tips glow with a colors of a rainbow!
  - type: textarea
    attributes:
      label: Screenshots and Videos
      description: If applicable, add screenshots or videos to help explain your suggestion.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for suggestion!"